[default]

# https://github.com/crate-ci/typos/issues/915
locale = "en-au"

extend-ignore-re = [
    '^[ \t]*-----BEGIN PGP PUBLIC KEY BLOCK-----.*^[ \t]*-----END PGP PUBLIC KEY BLOCK-----',
    '^[ \t]*initialHashedPassword[ \t]*=[ \t]*.*$',
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$"
]

[default.extend-words]

# HACK: Regex is busted.
"Pn" = "Pn"

CAF = "CAF"
NCE = "NCE"
aci = "aci"
analyze = "analyze"
authorize = "authorize"
authorized = "authorized"
center = "center"
cros = "cros"
customization = "customization"
customizations = "customizations"
guage = "guage"
hashi = "hashi"
hashicorp = "hashicorp"
hda = "hda"
initialization = "initialization"
initialize = "initialize"
initialized = "initialized"
initializing = "initializing"
maximize = "maximize"
normalization = "normalization"
normalized = "normalized"
optimization = "optimization"
optimizations = "optimizations"
optimized = "optimized"
organization = "organization"
organizations = "organizations"
organize = "organize"
prioritize = "prioritize"
randomize = "randomize"
randomized = "randomized"
recognize = "recognize"
specializing = "specializing"
synchronized = "synchronized"
utilize = "utilize"

[files]

ignore-vcs = true

extend-exclude = [
  "*.drawio",
  ".devenv",
  ".direnv",
  ".git",
  "secrets",
  "vendor"
]
