---
##################################################
# Name: devenv.yaml
# Description: Workflow for Developer Environment Testing
##################################################

name: Devenv

# prettier-ignore
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "main"
      - "master"
      - "trunk"
    paths:
      - .github/workflows/devenv.yaml
      - devenv.nix
      - devenv.yaml
      - devenv.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: write

env:
  # GitHub
  PROJECT: ${{ github.repository }}
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  # Nix
  NIXPKGS_ALLOW_UNFREE: 1
  CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  CI: "true"
  SECRETSPEC_PROVIDER: env
  SECRETSPEC_REASON: ci-workflow

defaults:
  run:
    shell: bash

jobs:
  ##################################################
  # Test the Development environment shell
  ##################################################

  test:
    name: Test

    runs-on:
      group: enterprise/bingamon-lab
      labels: [self-hosted, linux, x64]

    timeout-minutes: 60
    continue-on-error: false

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: false
          submodules: recursive

      - id: setup_devenv
        name: Set up devenv
        uses: tars-cloud/actions/composite/setup-devenv@de946ad3f732657100a3b7e6262baee5bb2d2b0a # v3.0.1

      - id: prek_run
        name: Run Pre-commit Hooks (all files)
        uses: tars-cloud/actions/composite/run-devenv@de946ad3f732657100a3b7e6262baee5bb2d2b0a # v3.0.1
        with:
          run: prek run --all-files --show-diff-on-failure

      - id: devenv_test
        name: Devenv test
        uses: tars-cloud/actions/composite/run-devenv@de946ad3f732657100a3b7e6262baee5bb2d2b0a # v3.0.1
        with:
          run: devenv --no-tui test

      - id: devenv_status
        name: Report devenv status
        if: always()
        uses: tars-cloud/actions/composite/report-status@de946ad3f732657100a3b7e6262baee5bb2d2b0a # v3.0.1
        with:
          results: |
            setup=${{ steps.setup_devenv.outcome }}
            hooks=${{ steps.prek_run.outcome }}
            test=${{ steps.devenv_test.outcome }}
          publish-status: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          status-context: Devenv
          reporting-errors: fail
          fail-on-error: "true"
