---
##################################################
# Name: update.yaml
# Description: Workflow for Updating Developer Environment
##################################################

name: Devenv Update

# prettier-ignore
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      dry_run:
        description: Validate dependency updates without creating a pull request
        type: boolean
        default: false

concurrency:
  group: devenv-update-lock
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  update:
    uses: tars-cloud/actions/.github/workflows/consumer-devenv-update.yaml@de946ad3f732657100a3b7e6262baee5bb2d2b0a # v3.0.1
    with:
      runs-on: '{"group":"enterprise/bingamon-lab","labels":["self-hosted","linux","x64"]}'
      submodules: true
      branch: update-devenv-lock
      title: "chore: Update devenv.lock"
      labels: dependencies,semver none
      assignees: MAHDTech
      reviewers: MAHDTech
      dry-run: ${{ inputs.dry_run || false }}
    secrets:
      app-id: ${{ secrets.CI_APP_ID }}
      app-private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
