---
##################################################
# Name: trivy.yaml
# Description: Workflow for Trivy
##################################################

##################################################
# NOTES:
#       This workflow integrates Trivy with GitHub's code scanning feature.
#       Trivy is a simple and comprehensive vulnerability scanner from Aqua Security.
#       Visit https://github.com/aquasecurity/trivy for further information
#
##################################################

name: Trivy

# prettier-ignore
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - "main"
      - "master"
      - "trunk"
    paths-ignore:
      - "*.md"
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  security-events: write
  statuses: write

jobs:
  scan:
    uses: tars-cloud/actions/.github/workflows/consumer-trivy.yaml@de946ad3f732657100a3b7e6262baee5bb2d2b0a # v3.0.1
    with:
      runs-on: '{"group":"enterprise/bingamon-lab","labels":["self-hosted","linux","x64"]}'
      submodules: true
      fail-on-findings: false
      publish-status: true
      status-context: Trivy
